---
title: "Additional Models"
author: "Justin Sarna"
date: "April 14, 2017"
output: html_document
---

```{r}
# Load the necessary libraries
library(ggplot2)
library(useful)
library(caret)
library(ISLR)
library(scales)
library(plyr)
library(rpart)
library(rpart.plot)
library(class)
library(MuMIn)
library(caret)
```

```{r}
# code from hw4 to be used for creating additional models
acs$HighIncome <- as.numeric(with(acs, FamilyIncome >= 250000))
acs$foodstamp_binary <- ifelse(acs$FoodStamp == "Yes",1,0) # (yes = 1, no = 0)
acs$own_home <- ifelse(acs$OwnRent == "Rented",0, ifelse(acs$FamilyIncome == "Mortgage",1,2)) # (own = 1, rent = 0)
acs$family_type_cat <- ifelse(acs$FamilyType == "Married",1, ifelse(acs$FamilyIncome == "Female Head",2,3))
# married = 1, male head = 2, female head = 3
acs$InsuranceHigh <- (acs$Insurance > 1000) * 1
acs$NumWorkers2 <- (acs$NumWorkers == 2) * 1
acs$HouseCostsHigh <- (acs$HouseCosts > 1000) * 1
acs$high_electric <- (acs$ElectricBill > 350) * 1
# Break it into a training and test set with an 80/20 split.
set.seed(447)
testrecs <- sample(nrow(acs),0.2 * nrow(acs))
acs_test <- acs[testrecs,]
acs_fit <- acs[-testrecs,]  
# Create binary variable where 1 = not on food stamps & not renting & married
acs$HI_pred1 <- 0
acs$HI_pred1[acs_test$FoodStamp == 'No' & acs_test$OwnRent != 'Rented' & acs_test$FamilyType == 'Married'] <- 1
acs$null_model <- 0
```
#### glm dredge
```{r}
# be aware that this takes time to run. It is worth the wait BUT frowned upon when used due to spurious results and inference
glm1 <- glm(HighIncome ~ Insurance + HouseCosts + ElectricBill + FamilyType + FoodStamp + OwnRent + NumBedrooms + NumRooms, family=binomial(logit), na.action = "na.fail", data=acs_fit)
dd_glm1 <- dredge(glm1)
```

```{r}
summary(glm1)
dd_glm1
```
```{r}
# best supported models
subset(dd_glm1, delta < 5)

# best model
subset(dd_glm1, delta == 0)

# calculate variable importance weights
importance(dd_glm1) 
```
### lm dredge
```{r}
lm1 <- lm(FamilyIncome ~ Insurance + HouseCosts + ElectricBill + family_type_cat + FoodStamp + own_home + NumBedrooms + NumRooms, na.action = "na.fail", data=acs_fit)
dd_lm1 <- dredge(lm1)
summary(lm1)
dd_lm1
```
```{r}
# best supported models
subset(dd_lm1, delta <5)

# best model
subset(dd_lm1, delta == 0)

# calculate variable importance weights
importance(dd_lm1) 
```
# Multilevel Model Specification
#### lme()

```{r}
summary(acs_norm2)
```
```{r}
library(nlme)
mms1 <- lme(fixed = FamilyIncome ~ 1, method = "ML", data = acs_fit, random =~ 1 | HouseCosts)
summary(mms1)
```
```{r}
mms2 <- lme(fixed = HighIncome ~ FamilyType, data = acs_fit, random =~ FamilyType | HouseCosts)
summary(mms2)
```
# Cluster Analysis
```{r}
normalize <- function(x) {
num <- x - min(x)
denom <- max(x) - min(x)
return (num/denom)
}
```
```{r}
acs_numericals2 <- data.frame(acs$NumBedrooms, acs$NumChildren, acs$NumPeople, acs$NumRooms, acs$NumVehicles, acs$NumWorkers, acs$HouseCosts, acs$ElectricBill, acs$Insurance)
acs_norm2 <- as.data.frame(lapply(acs_numericals2[1:8], normalize))
acs_norm2$HighIncome1 <- c(acs$HighIncome)
acs_norm2$FamilyIncome <- c(acs$FamilyIncome)
```


vars_to_use <- colnames(acs_norm2)[-1]
pmatrix <- scale(acs_fit[,vars_to_use])
pcenter <- attr(pmatrix, "scaled:center")
pscale <- attr(pmatrix, "scaled:scale")

```{r}
distance <- dist(acs_norm2, method ="euclidian")
pfit <- hclust(distance, method = "ward")
cluster1 <- plot(pfit, labels = acs_fit$FamilyIncome)
```

