---
title: "cluster_analysis"
author: "Justin Sarna"
date: "April 14, 2017"
output: html_document
---

```{r}
acs <- read.table("http://jaredlander.com/data/acs_ny.csv",sep=",",
                  header=TRUE, stringsAsFactors=TRUE)
```

```{r}
# Load the necessary libraries
library(ggplot2)
library(useful)
library(caret)
library(ISLR)
library(scales)
library(plyr)
library(rpart)
library(rpart.plot)
library(class)
library(MuMIn)
library(caret)
```
# Create some new variables based on EDA
```{r}
# code from hw4 to be used for creating additional models
acs$HighIncome <- as.numeric(with(acs, FamilyIncome >= 250000))
acs$foodstamp_binary <- ifelse(acs$FoodStamp == "Yes",1,0) # (yes = 1, no = 0)
acs$own_home <- ifelse(acs$OwnRent == "Rented",0, ifelse(acs$FamilyIncome == "Mortgage",1,2)) # (own = 1, rent = 0)
acs$family_type_cat <- ifelse(acs$FamilyType == "Married",1, ifelse(acs$FamilyIncome == "Female Head",2,3))
# married = 1, male head = 2, female head = 3
acs$InsuranceHigh <- (acs$Insurance > 1000) * 1
acs$NumWorkers2 <- (acs$NumWorkers == 2) * 1
acs$HouseCostsHigh <- (acs$HouseCosts > 1000) * 1
acs$high_electric <- (acs$ElectricBill > 350) * 1
# Break it into a training and test set with an 80/20 split.
set.seed(447)
testrecs <- sample(nrow(acs),0.2 * nrow(acs))
acs_test <- acs[testrecs,]
acs_fit <- acs[-testrecs,]  
# Create binary variable where 1 = not on food stamps & not renting & married
acs$HI_pred1 <- 0
acs$HI_pred1[acs_test$FoodStamp == 'No' & acs_test$OwnRent != 'Rented' & acs_test$FamilyType == 'Married'] <- 1
acs$null_model <- 0
```

# Cluster Analysis

```{r}
normalize <- function(x) {
num <- x - min(x)
denom <- max(x) - min(x)
return (num/denom)
}
```
```{r}
acs_numericals2 <- data.frame(acs$HouseCosts, acs$ElectricBill, acs$Insurance)
acs_norm2 <- as.data.frame(lapply(acs_numericals2[1:3], normalize))
acs_norm2$FamilyType1 <- c(acs$FamilyType)
acs_norm2$HighIncome <- c(acs$HighIncome)
```

```{r}
distance <- dist(acs_norm2, method ="euclidean")
pfit <- hclust(distance, method = "ward")
```
```{r}
cluster1 <- plot(pfit, labels = acs_norm2$FamilyType)
rect.hclust(pfit, k=5)
```
```{r}
acs_norm2$groups <- cutree(pfit, k=5)
```

####Display each goup with number of observations per group
```{r}
table(groups)
#print_clusters(groups, 5)
```

## Use groups as new variable in model
```{r}
library(mgcv)
```
```{r}
# first must add HighIncome to acs_norm2 data frame
#acs_norm_tes$HighIncome <- 
gam_mod_cluster <- gam(HighIncome ~ s(acs.Insurance) + s(acs.HouseCosts) + s(acs.ElectricBill) + groups, 
                data = acs_norm2, family=binomial(link="logit"))
summary(gam_mod_cluster)
gam_cluster_adjR <- summary(gam_mod_cluster)$r.sq
gam_cluster_aic <- AIC(gam_mod_cluster)
acs_norm2$gam_cluster_HighIncome <- ifelse(gam_mod_cluster$fit > .5 ,1,0)
gam_cluster_cm <- confusionMatrix(as.factor(acs_norm2$gam_cluster_HighIncome), as.factor(acs_norm2$HighIncome),
                                  positive = "1")
gam_cluster_cm
gam_cluster_adjR
gam_cluster_aic
```
```{r}
cluster_pred <- predict(gam_mod_cluster, acsNorm2_valid, type="class" )
```


