---
title: "cluster_analysis"
author: "Justin Sarna"
date: "April 14, 2017"
output: html_document
---
```{r}
# Load the necessary libraries
library(ggplot2)
library(useful)
library(caret)
library(ISLR)
library(scales)
library(plyr)
library(rpart)
library(rpart.plot)
library(class)
library(MuMIn)
library(caret)
```
# Create some new variables based on EDA
```{r}
# code from hw4 to be used for creating additional models
acs$HighIncome <- as.numeric(with(acs, FamilyIncome >= 250000))
acs$foodstamp_binary <- ifelse(acs$FoodStamp == "Yes",1,0) # (yes = 1, no = 0)
acs$own_home <- ifelse(acs$OwnRent == "Rented",0, ifelse(acs$FamilyIncome == "Mortgage",1,2)) # (own = 1, rent = 0)
acs$family_type_cat <- ifelse(acs$FamilyType == "Married",1, ifelse(acs$FamilyIncome == "Female Head",2,3))
# married = 1, male head = 2, female head = 3
acs$InsuranceHigh <- (acs$Insurance > 1000) * 1
acs$NumWorkers2 <- (acs$NumWorkers == 2) * 1
acs$HouseCostsHigh <- (acs$HouseCosts > 1000) * 1
acs$high_electric <- (acs$ElectricBill > 350) * 1
# Break it into a training and test set with an 80/20 split.
set.seed(447)
testrecs <- sample(nrow(acs),0.2 * nrow(acs))
acs_test <- acs[testrecs,]
acs_fit <- acs[-testrecs,]  
# Create binary variable where 1 = not on food stamps & not renting & married
acs$HI_pred1 <- 0
acs$HI_pred1[acs_test$FoodStamp == 'No' & acs_test$OwnRent != 'Rented' & acs_test$FamilyType == 'Married'] <- 1
acs$null_model <- 0
```

# Cluster Analysis

```{r}
acs_numericals2 <- data.frame(acs$HouseCosts, acs$ElectricBill, acs$Insurance)
acs_norm2 <- as.data.frame(lapply(acs_numericals2[1:3], normalize))
#acs_norm2$HighIncome1 <- c(acs$HighIncome)
#acs_norm2$FamilyIncome1 <- c(acs$FamilyIncome)
acs_norm2$FamilyType1 <- c(acs$FamilyType)
```


vars_to_use <- colnames(acs_norm2)[-1]
pmatrix <- scale(acs_norm2[,vars_to_use])
pcenter <- attr(pmatrix, "scaled:center")
pscale <- attr(pmatrix, "scaled:scale")


```{r}
distance <- dist(acs_norm2, method ="euclidean")
pfit <- hclust(distance, method = "ward")
```
```{r}
cluster1 <- plot(pfit, labels = acs_norm2$FamilyType)
rect.hclust(pfit, k=5)
```
```{r}
groups <- cutree(pfit, k=5)
print_clusters <- function(labels,k){
  for(i in 1:k){
    print(paste("cluster", i))
    print(acs_norm2[labels==i,c("HouseCosts","ElectricBill", "Insurance","FamilyType")])
  }
}
```
```{r}
print_clusters(groups, 5)
```