---
title: "random_forest"
author: "Justin Sarna"
date: "April 14, 2017"
output: html_document
---

```{r}
# Load the necessary libraries
library(ggplot2)
library(useful)
library(caret)
library(ISLR)
library(scales)
library(plyr)
library(rpart)
library(rpart.plot)
library(class)
library(MuMIn)
library(caret)
```

```{r}
# code from hw4 to be used for creating additional models
acs$HighIncome <- as.numeric(with(acs, FamilyIncome >= 250000))
acs$foodstamp_binary <- ifelse(acs$FoodStamp == "Yes",1,0) # (yes = 1, no = 0)
acs$own_home <- ifelse(acs$OwnRent == "Rented",0, ifelse(acs$FamilyIncome == "Mortgage",1,2)) # (own = 1, rent = 0)
acs$family_type_cat <- ifelse(acs$FamilyType == "Married",1, ifelse(acs$FamilyIncome == "Female Head",2,3))
# married = 1, male head = 2, female head = 3
acs$InsuranceHigh <- (acs$Insurance > 1000) * 1
acs$NumWorkers2 <- (acs$NumWorkers == 2) * 1
acs$HouseCostsHigh <- (acs$HouseCosts > 1000) * 1
acs$high_electric <- (acs$ElectricBill > 350) * 1
# Break it into a training and test set with an 80/20 split.
set.seed(447)
testrecs <- sample(nrow(acs),0.2 * nrow(acs))
acs_test <- acs[testrecs,]
acs_fit <- acs[-testrecs,]  
# Create binary variable where 1 = not on food stamps & not renting & married
acs$HI_pred1 <- 0
acs$HI_pred1[acs_test$FoodStamp == 'No' & acs_test$OwnRent != 'Rented' & acs_test$FamilyType == 'Married'] <- 1
acs$null_model <- 0
```
# Random Forests
```{r}
library(randomForest)
```
```{r}
loglikelihood <- function(y,py) {
  pysmooth <- ifelse(py==0, 1e-12,
                     ifelse(py==1, 1-1e-12,py))
  sum(y * log(pysmooth) + (1-y)*log(1 - pysmooth))
}
```

```{r}
accuracyMeasures <- function(pred, truth, name="model"){
  dev.norm <- -2*loglikelihood(as.numeric(truth),pred)/length(pred)
  ctable <- table(truth=truth,
                  pred=(pred>.5))
  accuracy <- sum(diag(ctable))/sum(ctable)
  precision <- ctable[2,2]/sum(ctable[,2])
  recall <- ctable[2,2]/sum(ctable[,2])
  f1 <- precision*recall
  data.frame(model=name,accuracy=accuracy,f1=f1,dev.norm)
}
```

```{r}
randtree_mod1 <- randomForest(x=acs_fit[3:18], 
                              y=acs_fit$FamilyIncome,
                              ntree=100,
                              nodesize = 7,
                              importance=T)
```
```{r}
accuracyMeasures(predict(randtree_mod1, newdata=acs_fit, [,'FamilyIncome'],
                 acs_fit$FamilyIncome == 'FamilyIncome', name='random forest, train')
```