---
title: "README"
author: "Justin Sarna"
date: "April 20, 2017"
output: html_document

GitHub: https://github.com/jbsarna/Predictive_Modeling
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Predictive Modeling Project

## General Information

1) The intentions and purpose of this project
    
    + The first goal was to dig deeper into predictive modeling techniques beyond the scope of hw4
    + Find new methods, formulas, techniques that were not discussed in class
    + Use cross validation with all models to determine which models predicted the best
    + As an end product, I wanted one final output that displayed all the models with metrics for easy comparison
    + I structured the code in a way that it could be used in a "teaching" setting. Each process/method is labeled and explained
    + Lastly, I wanted to incorporate the use of GitHub for my project

2) Don't worry if a code chunk takes a little time to execute. I only included models/code that would execute in less than
    1 minute (most execute in just a matter of seconds)

#### Understanding my code format/style

    '#' = comments

    '##' = code that has been "commented out", but could be useful for deeper analysis/understanding of my process

## How to "work" through my R-project

There are 4 different ways to work through my project from start to finish


1) Knitted html files

    + Each individual method rmd has been knitted to html and provided
    + The complete project (pred_model_git.rmd) has also been knitted to html
    + This is probably the most efficient way to work through the entire project because it does not require executing any code
    + To see a summary with general comments on predictive modeling scroll to the bottme of the pred_model_git.html file


2) All at once - pred_model_git.rmd
  
    + This is one single rmd file that includes all of the methods
    + You can start at the top and work through my entire process from start to finish
    + Ends with a collection of important metrics for each method & model displayed together for easy analysis
    + I provide comments/text throughout the code to explain the code and process
    + To see a summary comparison with general comments on predictive modeling scroll to the bottom of the pred_model_git.rmd file
  

3) Individual methods - pred_model_git.Rproj
  
    + Each method has its own rmd file in my R project
    + You can work through each method individually this way
    + Each method's rmd file ends with a collection of important metrics for each model using the respective method
    + The rmd file names are self explanatory, which makes this option easy to use
    + I provide comments/text throughout the code to explain the code and process


4) GitHub - https://github.com/jbsarna/Predictive_Modeling

    + The above link will take you to my GitHub account
    + All of the files in my R project are available on my GitHub account
    + This is arguably the easiest way to "read" my code
    + Downside is that you can't view any of the outputs
    + This is a good option if you are using dual monitors - have GitHub on one and R on the other
    + To see a summary with general comments on predictive modeling scroll to the bottom of the pred_model_git file in the start_here folder
    + This would especially be useful as a "student" referring to this for future use in class or "teaching" these methods
    + This is also going to be very useful for me personally when doing predictive modeling or using R in general in the future
    + Lastly, I am happy to share this work in hopes that others can benefit from it...much in the same way I have from others. So it only seemed fitting to make it publicly available


# Best Model

#### My best model ended up being a Random Forest with prediction accuracy of .9903 and sensitivity of .8382!

    rand_forest <- randomForest(HighIncome ~ Insurance + ElectricBill + HouseCosts + NumBedrooms + ElectricBill + 
                            NumVehicles + NumChildren + NumPeople + FoodStamp + Language + NumRooms + OwnRent + 
                            NumUnits, data=acs_test, mtry=12, importance = TRUE, na.action = na.omit)
